#ifndef TFT_320x240_H
#define TFT_320x240_H

#define TFT_SCREEN_ROTATION   3
#define CANVAS_WIDTH 320 
#define CANVAS_HEIGHT 240 

#define TFT_SPLASH_SCREEN_DURATION 2000


/** Header: Battery     Units    Mode    diode 
 * 
 * 
 * 
 * Body:  HV   DIGITS 
 * 
 * 
 * 
 * 
 * Footer: BAR graph 
 */




#define BETWEEN_ZONES_BUFFER_HEIGHT 6
#define WITHIN_ZONE_BUFFER_HEIGHT   3
#define HORIZONTAL_BUFFER_WIDTH 8


// positions of the header elements 
#define X_BATTERY (CANVAS_WIDTH - BATTERY_WIDTH - HORIZONTAL_BUFFER_WIDTH)
#define Y_BATTERY ((H_MODE_LG - BATTERY_HEIGHT) >> 1)  

#define X_MODE ((CANVAS_WIDTH- W_MODE_LG)>>1)
#define Y_MODE 0

#define X_UNITS (X_MEASUREMENTS + MEASUREMENTS_WIDTH + HORIZONTAL_BUFFER_WIDTH)   
#define Y_UNITS (Y_MEASUREMENTS + 2*(H_DIGIT_LG - H_UNIT_LG))

#define X_DIODE HORIZONTAL_BUFFER_WIDTH
#define Y_DIODE ((H_MODE_LG - DIODE_HEIGHT)>>1)

// Position of the body elements 
#define X_MEASUREMENTS  HORIZONTAL_BUFFER_WIDTH
#define Y_MEASUREMENTS  (Y_BATTERY+H_MODE_LG+4*BETWEEN_ZONES_BUFFER_HEIGHT)
#define MEASUREMENTS_WIDTH (HV_WIDTH+W_SIGN_LG+4*(W_DIGIT_LG)+W_DP_LG)
#define MEASUREMENTS_HEIGHT H_DIGIT_LG

// Analog meter 
#define X_ANALOG_METER 5
#define Y_ANALOG_METER (CANVAS_HEIGHT - ANALOG_METER_HEIGHT - 5)
#define ANALOG_METER_WIDTH (CANVAS_WIDTH-10)
#define ANALOG_METER_HEIGHT 20
 

#define TFT_LIGHTBLUE 0x7BEF
#define TFT_SALMON 0xFC8E
#define TFT_DARKRED 0x8000
#define TFT_LIGHTMUSTARD 0xEFE0
#define TFT_LIGHTGREEN 0x97E6


#endif // TFT_320x240_H
