#ifndef TFT_320x240_H
#define TFT_320x240_H



//#define TFT_WIDTH   220
//#define TFT_HEIGHT  176
#define TFT_SCREEN_ROTATION   3

// THE ILI9341 is 320x240 and it selects the WIDTH and HEIGHT by the rotation 
//#define CANVAS_WIDTH TFT_WIDTH // (IS_ODD(TFT_SCREEN_ROTATION) ? TFT_HEIGHT : TFT_WIDTH)
//#define CANVAS_HEIGHT TFT_HEIGHT // (IS_ODD(TFT_SCREEN_ROTATION) ? TFT_WIDTH : TFT_HEIGHT)

#define CANVAS_WIDTH 220  //314
#define CANVAS_HEIGHT 240 //176

#define TFT_SPLASH_SCREEN_DURATION 2000

#define BETWEEN_ZONES_BUFFER_HEIGHT 6
#define WITHIN_ZONE_BUFFER_HEIGHT   3

#define X_ZONE_0  0
#define Y_ZONE_0  0
#define ZONE_0_WIDTH CANVAS_WIDTH
#define ZONE_0_HEIGHT HV_HEIGHT

#define X_ZONE_1  0
#define Y_ZONE_1  (Y_ZONE_0+ZONE_0_HEIGHT+BETWEEN_ZONES_BUFFER_HEIGHT)
#define ZONE_1_WIDTH  CANVAS_WIDTH
#define ZONE_1_HEIGHT H_DIGIT_LG

#define X_ZONE_2 0
#define Y_ZONE_2  (Y_ZONE_1+ZONE_1_HEIGHT+BETWEEN_ZONES_BUFFER_HEIGHT)
#define ZONE_2_WIDTH  CANVAS_WIDTH
#define ZONE_2_HEIGHT H_DIGIT_SM

#define X_ZONE_3 0
#define Y_ZONE_3  (Y_ZONE_2+ZONE_2_HEIGHT+BETWEEN_ZONES_BUFFER_HEIGHT)
#define ZONE_3_WIDTH  CANVAS_WIDTH
#define ZONE_3_HEIGHT H_DIGIT_SM

/** RELATIVE COORDINATES IN ZONE_0 **/
#define REL_IN_ZONE_X_HIGH_VOLTAGE  0
#define REL_IN_ZONE_Y_HIGH_VOLTAGE  0

#define REL_IN_ZONE_X_DIODE  ((ZONE_0_WIDTH-DIODE_WIDTH)>>1)
#define REL_IN_ZONE_Y_DIODE  0

#define REL_IN_ZONE_X_BATTERY (ZONE_0_WIDTH-BATTERY_WIDTH)
#define REL_IN_ZONE_Y_BATTERY 0


/** RELATIVE COORDINATES IN ZONE_1 **/

#define REL_IN_ZONE_X_MODE    7
#define REL_IN_ZONE_Y_MODE    0

#define REL_IN_ZONE_X_UNITS   7
#define REL_IN_ZONE_Y_UNITS   (WITHIN_ZONE_BUFFER_HEIGHT+H_MODE_SM)


#endif // TFT_320x240_H
