#ifndef TFT_320x240_H
#define TFT_320x240_H

#define TFT_SCREEN_ROTATION   3
#define CANVAS_WIDTH 320 
#define CANVAS_HEIGHT 240 

#define TFT_SPLASH_SCREEN_DURATION 2000


/** Header: Battery     Units    Mode    diode 
 * 
 * 
 * 
 * Body:  HV   DIGITS 
 * 
 * 
 * 
 * 
 * Footer: BAR graph 
 */




#define BETWEEN_ZONES_BUFFER_HEIGHT 6
#define WITHIN_ZONE_BUFFER_HEIGHT   3


// positions of the header elements 
#define X_BATTERY (CANVAS_WIDTH - BATTERY_WIDTH)
#define Y_BATTERY 0

#define X_UNITS ((CANVAS_WIDTH>>1) - W_UNIT_LG - 3)
#define Y_UNITS 0

#define X_MODE ((CANVAS_WIDTH>>1) + W_MODE_LG + 3)
#define Y_MODE 0

#define X_DIODE 0
#define Y_DIODE 0

// Position of the body elements 
#define X_MEASUREMENTS  0
#define Y_MEASUREMENTS  (Y_BATTERY+H_MODE_LG+BETWEEN_ZONES_BUFFER_HEIGHT)
#define MEASUREMENTS_WIDTH (HV_WIDTH+5+W_SIGN_LG+4*(W_DIGIT_LG)+W_DP_LG)
#define MEASUREMENTS_HEIGHT H_DIGIT_LG





// #define Y_ZONE_0  0
// #define ZONE_0_WIDTH CANVAS_WIDTH
// #define ZONE_0_HEIGHT HV_HEIGHT

// #define X_ZONE_1  0
// #define Y_ZONE_1  (Y_ZONE_0+ZONE_0_HEIGHT+BETWEEN_ZONES_BUFFER_HEIGHT)
// #define ZONE_1_WIDTH  (HV_WIDTH+4*(W_DIGIT_LG)+W_SIGN_LG+W_DP_LG+W_MODE_SM+W_UNIT_LG)
// #define ZONE_1_HEIGHT H_DIGIT_LG

// #define X_ZONE_2 0
// #define Y_ZONE_2  (Y_ZONE_1+ZONE_1_HEIGHT+BETWEEN_ZONES_BUFFER_HEIGHT)
// #define ZONE_2_WIDTH  CANVAS_WIDTH
// #define ZONE_2_HEIGHT H_DIGIT_SM

// #define X_ZONE_3 0
// #define Y_ZONE_3  (Y_ZONE_2+ZONE_2_HEIGHT+BETWEEN_ZONES_BUFFER_HEIGHT)
// #define ZONE_3_WIDTH  CANVAS_WIDTH
// #define ZONE_3_HEIGHT H_DIGIT_SM

// /** RELATIVE COORDINATES IN ZONE_0 **/
// #define REL_IN_ZONE_X_HIGH_VOLTAGE  0
// #define REL_IN_ZONE_Y_HIGH_VOLTAGE  0

// #define REL_IN_ZONE_X_DIODE  ((ZONE_0_WIDTH-DIODE_WIDTH)>>1)
// #define REL_IN_ZONE_Y_DIODE  0

// #define REL_IN_ZONE_X_BATTERY (ZONE_0_WIDTH-BATTERY_WIDTH)
// #define REL_IN_ZONE_Y_BATTERY 0


// /** RELATIVE COORDINATES IN ZONE_1 **/

// #define REL_IN_ZONE_X_MODE    7
// #define REL_IN_ZONE_Y_MODE    0

// #define REL_IN_ZONE_X_UNITS   7
// #define REL_IN_ZONE_Y_UNITS   (WITHIN_ZONE_BUFFER_HEIGHT+H_MODE_SM)



// /** ABSOLUTE COORDINATES **/
// #define X_HIGH_VOLTAGE  (X_ZONE_0 + REL_IN_ZONE_X_HIGH_VOLTAGE)
// #define Y_HIGH_VOLTAGE  (Y_ZONE_0 + REL_IN_ZONE_Y_HIGH_VOLTAGE)

// #define X_DIODE  (X_ZONE_0 + REL_IN_ZONE_X_DIODE)
// #define Y_DIODE  (Y_ZONE_0 + REL_IN_ZONE_Y_DIODE)

// #define X_BATTERY (X_ZONE_0 + REL_IN_ZONE_X_BATTERY)
// #define Y_BATTERY (Y_ZONE_0 + REL_IN_ZONE_Y_BATTERY)

// #define X_MODE (X_ZONE_1 + REL_IN_ZONE_X_MODE)
// #define Y_MODE (Y_ZONE_1 + REL_IN_ZONE_Y_MODE)

// #define X_UNITS (X_ZONE_1 + REL_IN_ZONE_X_UNITS)
// #define Y_UNITS (Y_ZONE_1 + REL_IN_ZONE_Y_UNITS)

#endif // TFT_320x240_H
